version: "3"

services:
  client:
    image: nginx
    ports:
      - 1234:80
    volumes:
      - ./src:/usr/share/nginx/html
    deploy:
      placement:
        constraints:
          - node.role == manager
